PHILIPS_BLUE = "#0B5ED7"
DARK_BLUE = "#00126E"
LIGHT_BLUE = "#BDF0FF"
CYAN = "#9CF6FB"
CORAL = "#FF6F61"
COOL_GRAY = "#F3F6FA"
WHITE = "#FFFFFF"
DARK_TEXT = "#111827"
MID_TEXT = "#4B5563"
LIGHT_BORDER = "#D7DEE8"
GRID_LINE = "#E6EBF2"
SOFT_BLUE = "#EEF6FF"
SOFT_CORAL = "#FFDEDB"
CARD_SHADOW = "#D9E2EF"

FIGURE_SIZE_16_9 = (16, 9)
DPI = 200

KPI_COLORS = [
    PHILIPS_BLUE,
    DARK_BLUE,
    CYAN,
    CORAL,
]

INTENSITY_COLORS = {
    "Very High": DARK_BLUE,
    "High": PHILIPS_BLUE,
    "Moderate": CYAN,
    "Low": LIGHT_BLUE,
}
